version: '2.1'

services:
    postgres:
        image: postgres:9.6
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=airbnb
            - POSTGRES_PASSWORD=airbnb
            - POSTGRES_DB=airbnb
        volumes:
            - /tmp/postgres-data:/var/lib/postgresql/data

    pgweb:
        container_name: pgweb
        restart: always
        image: sosedoff/pgweb
        ports: 
            - "8081:8081" 
        links: 
            - postgres:postgres  # my database container is called postgres, not db
        environment:
            - DATABASE_URL=postgres://airbnb:airbnb@postgres:5432/airbnb?sslmode=disable
        depends_on:
            - postgres